# Generated by Django 5.2.17 on 2026-09-28 16:49

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflinePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data hahú"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Data remata")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Nota"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fó husi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_permission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Investigadór",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorizasaun Offline",
                "verbose_name_plural": "Autorizasaun Offline",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Pesoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="Naran"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=4,
                        null=True,
                        verbose_name="Sexu",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nu. Telf."
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=users.models.pesoal_foto_path,
                        verbose_name="Foto",
                    ),
                ),
                (
                    "lian",
                    models.CharField(
                        choices=[
                            ("tet", "Tetun"),
                            ("pt", "Português"),
                            ("en", "English"),
                            ("id", "Bahasa Indonesia"),
                        ],
                        default="tet",
                        max_length=5,
                        verbose_name="Lian",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "munisipiu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pesoal",
                        to="custom.munisipiu",
                        verbose_name="Munisípiu Knaar",
                    ),
                ),
                (
                    "pos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pesoal",
                        to="custom.pozisaun",
                        verbose_name="Pozisaun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesoal",
                "verbose_name_plural": "Pesoal",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PesoalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True, verbose_name="Tenke troka password"
                    ),
                ),
                (
                    "pesoal",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesoaluser",
                        to="users.pesoal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Konta Pesoal",
                "verbose_name_plural": "Konta Pesoal",
            },
        ),
    ]
