# Generated by Django 5.2.17 on 2026-09-28 23:00

import django.db.models.deletion
import legal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kazu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DokumentuLegal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kategoria",
                    models.CharField(
                        choices=[
                            ("KARTA", "Karta / Reklamasaun"),
                            ("DEKLARASAUN", "Deklarasaun Testemuña"),
                            ("SERTIFIKADU", "Sertifikadu / Títulu Rai"),
                            ("DESIZAUN", "Desizaun Tribunál / Autoridade"),
                            ("KONTRATU", "Kontratu / Akordu"),
                            ("LEI", "Lei / Regulamentu"),
                            ("SELUK", "Seluk"),
                        ],
                        max_length=12,
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "titulu",
                    models.CharField(max_length=200, verbose_name="Títulu dokumentu"),
                ),
                ("deskrisaun", models.TextField(blank=True, verbose_name="Deskrisaun")),
                (
                    "data_dokumentu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data dokumentu"
                    ),
                ),
                (
                    "konfidensial",
                    models.BooleanField(
                        default=False,
                        help_text="Ofisiál Legál no Superadmin deit mak bele haree",
                        verbose_name="Konfidensiál",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=legal.models.vault_path, verbose_name="File"
                    ),
                ),
                ("naran_orijinal", models.CharField(blank=True, max_length=200)),
                ("tamanu", models.PositiveIntegerField(default=0)),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                (
                    "versaun",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Versaun"),
                ),
                ("atual", models.BooleanField(db_index=True, default=True)),
                ("arkivadu", models.BooleanField(db_index=True, default=False)),
                ("arkivu_razaun", models.CharField(blank=True, max_length=255)),
                ("arkivu_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data upload"),
                ),
                (
                    "arkivu_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mamuk = dokumentu jerál (lei, regulamentu)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dokumentu_legal",
                        to="kazu.kazu",
                        verbose_name="Kazu",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload husi",
                    ),
                ),
                (
                    "versaun_anterior",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versaun_foun",
                        to="legal.dokumentulegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentu Legál",
                "verbose_name_plural": "Dokumentu Legál",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AsesuVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aksaun",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Upload"),
                            ("DOWNLOAD", "Download"),
                            ("VERSAUN", "Versaun foun"),
                            ("ARKIVU", "Arkivu"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dokumentu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asesu",
                        to="legal.dokumentulegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asesu Vault",
                "verbose_name_plural": "Asesu Vault",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="NotaLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipu",
                    models.CharField(
                        choices=[
                            ("ANALIZE", "Análize Legál"),
                            ("KONSELLU", "Konsellu ba Komunidade"),
                            ("MEDIASAUN", "Mediasaun"),
                            ("AUDIENSIA", "Audiénsia / Tribunál"),
                            ("AKSAUN", "Aksaun Seluk"),
                        ],
                        max_length=10,
                        verbose_name="Tipu",
                    ),
                ),
                ("testu", models.TextField(verbose_name="Nota")),
                (
                    "prazu",
                    models.DateField(
                        blank=True,
                        help_text="Sistema sei haruka lembrete loron 3 antes",
                        null=True,
                        verbose_name="Prazu / Data audiénsia",
                    ),
                ),
                ("remata", models.BooleanField(default=False, verbose_name="Remata")),
                (
                    "konfidensial",
                    models.BooleanField(default=False, verbose_name="Konfidensiál"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nota_legal",
                        to="kazu.kazu",
                        verbose_name="Kazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Legál",
                "verbose_name_plural": "Nota Legál",
                "ordering": ["remata", "prazu", "-created_at"],
            },
        ),
    ]
