# Generated by Django 5.2.17 on 2026-09-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipu",
                    models.CharField(
                        choices=[
                            ("KAZU_FOUN", "Kazu foun"),
                            ("KAZU_STATUS", "Status kazu muda"),
                            ("OFFLINE", "Autorizasaun offline"),
                            ("SISTEMA", "Sistema"),
                        ],
                        default="SISTEMA",
                        max_length=20,
                        verbose_name="Tipu",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Mensajen")),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="Link"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Urjente"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lee ona")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Husi",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ba",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifikasaun",
                "verbose_name_plural": "Notifikasaun",
                "ordering": ["-is_urgent", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_dd6756_idx",
                    )
                ],
            },
        ),
    ]
