# Generated by Django 5.2.17 on 2026-09-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="tipu",
            field=models.CharField(
                choices=[
                    ("KAZU_FOUN", "Kazu foun"),
                    ("KAZU_STATUS", "Status kazu muda"),
                    ("OFFLINE", "Autorizasaun offline"),
                    ("LEGAL", "Legál (aksaun / prazu)"),
                    ("SISTEMA", "Sistema"),
                ],
                default="SISTEMA",
                max_length=20,
                verbose_name="Tipu",
            ),
        ),
    ]
