# Generated by Django 5.2.17 on 2026-09-28 17:18

import django.db.models.deletion
import kazu.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kazu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kode",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="ID Kazu",
                    ),
                ),
                (
                    "titulu",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Títulu kazu"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("ONGOING", "Iha Terrenu"),
                            ("PENDING", "Hein Sinál"),
                            ("SYNCED", "Hein Verifikasaun"),
                            ("VERIFIED", "Verifikadu"),
                            ("APPROVED", "Aprovadu"),
                            ("COMPLETED", "Remata"),
                            ("REJECTED", "Rejeitadu"),
                            ("CANCELED", "Kanseladu"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                        verbose_name="Status Dadus",
                    ),
                ),
                (
                    "status_kazu",
                    models.CharField(
                        choices=[
                            ("ABERTU", "Abertu"),
                            ("INVESTIGASAUN", "Investigasaun"),
                            ("AKSAUN_LEGAL", "Aksaun Legál"),
                            ("TAKA", "Taka"),
                        ],
                        db_index=True,
                        default="ABERTU",
                        max_length=15,
                        verbose_name="Status Kazu",
                    ),
                ),
                (
                    "data_relatoriu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Relatóriu"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "gps_akurasia",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Akurasia GPS (m)"
                    ),
                ),
                (
                    "data_akontesimentu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Akontesimentu"
                    ),
                ),
                (
                    "tipu_seluk",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Seluk: favor esplika"
                    ),
                ),
                (
                    "deskrisaun",
                    models.TextField(blank=True, verbose_name="Deskrisaun Insidente"),
                ),
                (
                    "estragu_seluk",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Estragu seluk"
                    ),
                ),
                (
                    "urjente",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Urjente"
                    ),
                ),
                (
                    "konsentimentu",
                    models.BooleanField(
                        default=False,
                        verbose_name="Ema afetada fó konsentimentu informadu ba rekolla no uza dadus",
                    ),
                ),
                (
                    "observasaun",
                    models.TextField(blank=True, verbose_name="Observasaun Adisionál"),
                ),
                (
                    "la_publika",
                    models.BooleanField(
                        default=False, verbose_name="La publika iha portal públiku"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sinkron iha"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aldeia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.aldeia",
                        verbose_name="Aldeia",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kazu_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Investigadór",
                    ),
                ),
                (
                    "estragu",
                    models.ManyToManyField(
                        blank=True,
                        to="custom.estragupatrimoniu",
                        verbose_name="Estragu Patrimóniu",
                    ),
                ),
                (
                    "munisipiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kazu_set",
                        to="custom.munisipiu",
                        verbose_name="Munisípiu",
                    ),
                ),
                (
                    "nesesidade",
                    models.ManyToManyField(
                        blank=True,
                        to="custom.nesesidadeurjente",
                        verbose_name="Nesesidade Urjente",
                    ),
                ),
                (
                    "postu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.postuadministrativu",
                        verbose_name="Postu Administrativu",
                    ),
                ),
                (
                    "suku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.suku",
                        verbose_name="Suku",
                    ),
                ),
                (
                    "tipu_konflitu",
                    models.ManyToManyField(
                        blank=True,
                        to="custom.tipukonflitu",
                        verbose_name="Tipu Konflitu Rai",
                    ),
                ),
                (
                    "tipu_rai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.tipurai",
                        verbose_name="Tipu Rai",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kazu",
                "verbose_name_plural": "Kazu",
                "ordering": ["-urjente", "-created_at"],
                "permissions": [
                    ("verify_kazu", "Bele verifika kazu"),
                    ("approve_kazu", "Bele aprova kazu"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsidenteEviksaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loron_avizu",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Loron avizu antes eviksaun"
                    ),
                ),
                (
                    "forsa_seguransa",
                    models.BooleanField(
                        default=False, verbose_name="Forsa seguransa prezente"
                    ),
                ),
                (
                    "estragu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Estragu (uma / to'os / sasán)",
                    ),
                ),
                ("deskrisaun", models.TextField(blank=True, verbose_name="Narrativu")),
                (
                    "tipu_eviksaun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.tipueviksaun",
                        verbose_name="Tipu Eviksaun",
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insidente",
                        to="kazu.kazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insidente Eviksaun",
                "verbose_name_plural": "Insidente Eviksaun",
            },
        ),
        migrations.CreateModel(
            name="Evidensia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipu",
                    models.CharField(
                        choices=[
                            ("FOTO", "Foto"),
                            ("VIDEO", "Vídeo"),
                            ("DOKUMENTU", "Dokumentu Legál"),
                            ("DEKLARASAUN", "Deklarasaun Testemuña"),
                        ],
                        max_length=12,
                        verbose_name="Tipu",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=kazu.models.evidensia_path, verbose_name="File"
                    ),
                ),
                (
                    "naran",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Naran dokumentu"
                    ),
                ),
                (
                    "deskrisaun",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Deskrisaun"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data upload"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidensia",
                        to="kazu.kazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidénsia",
                "verbose_name_plural": "Evidénsia",
                "ordering": ["tipu", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AtorEnvolvidu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naran",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Naran atór"
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Papél iha insidente"
                    ),
                ),
                (
                    "tipu_ator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom.tipuator",
                        verbose_name="Tipu Atór",
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ator",
                        to="kazu.kazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atór Envolvidu",
                "verbose_name_plural": "Atór Envolvidu",
            },
        ),
        migrations.CreateModel(
            name="KazuHistoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipu",
                    models.CharField(
                        choices=[
                            ("DADUS", "Status Dadus"),
                            ("KAZU", "Status Kazu"),
                            ("EDITA", "Edita"),
                            ("LEE", "Lee"),
                        ],
                        default="DADUS",
                        max_length=6,
                    ),
                ),
                ("status_antes", models.CharField(blank=True, max_length=15)),
                ("status_foun", models.CharField(blank=True, max_length=15)),
                ("nota", models.TextField(blank=True, verbose_name="Razaun / Nota")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia",
                        to="kazu.kazu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Istória Kazu",
                "verbose_name_plural": "Istória Kazu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UmaKainAfetada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uma_kain",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Númeru Uma-Kain"
                    ),
                ),
                (
                    "total_ema",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Estimasaun Total Ema"
                    ),
                ),
                (
                    "mane",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mane"
                    ),
                ),
                (
                    "feto",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Feto"
                    ),
                ),
                (
                    "labarik",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Labarik"
                    ),
                ),
                (
                    "katuas_ferik",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Katuas-Ferik"
                    ),
                ),
                (
                    "defisiensia",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ema ho Defisiénsia"
                    ),
                ),
                (
                    "kazu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afetadu",
                        to="kazu.kazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uma-Kain Afetada",
                "verbose_name_plural": "Uma-Kain Afetada",
            },
        ),
        migrations.CreateModel(
            name="KazuSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tinan", models.PositiveSmallIntegerField()),
                ("last", models.PositiveIntegerField(default=0)),
                (
                    "munisipiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.munisipiu",
                    ),
                ),
            ],
            options={
                "unique_together": {("munisipiu", "tinan")},
            },
        ),
    ]
