# Generated by Django 5.2.17 on 2026-10-02 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kazu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kazu",
            name="gps_aproksimadu",
            field=models.BooleanField(default=False, verbose_name="GPS aproksimadu"),
        ),
        migrations.CreateModel(
            name="KazuImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naran_file", models.CharField(max_length=255, verbose_name="File")),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Pratinjau"),
                            ("REMATA", "Importa ona"),
                            ("KANSELA", "Kansela"),
                        ],
                        default="RASCUNHO",
                        max_length=10,
                    ),
                ),
                ("dadus", models.JSONField(default=list)),
                ("total", models.PositiveIntegerField(default=0)),
                ("total_ok", models.PositiveIntegerField(default=0)),
                ("total_aproksimadu", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("konfirma_iha", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Kazu",
                "verbose_name_plural": "Import Kazu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="kazu",
            name="importasaun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kazu_set",
                to="kazu.kazuimport",
                verbose_name="Import",
            ),
        ),
    ]
