# Generated by Django 5.2.17 on 2026-09-28 23:17

import django.db.models.deletion
import publiku.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publikasaun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipu",
                    models.CharField(
                        choices=[
                            ("POLICY", "Policy Brief"),
                            ("RELATORIU", "Relatóriu"),
                            ("INFOGRAFIKU", "Infográfiku"),
                        ],
                        default="POLICY",
                        max_length=12,
                        verbose_name="Tipu",
                    ),
                ),
                ("titulu", models.CharField(max_length=200, verbose_name="Títulu")),
                (
                    "rezumu",
                    models.TextField(max_length=600, verbose_name="Rezumu badak"),
                ),
                (
                    "lian",
                    models.CharField(
                        choices=[
                            ("tet", "Tetun"),
                            ("pt", "Português"),
                            ("en", "English"),
                            ("id", "Bahasa Indonesia"),
                        ],
                        default="tet",
                        max_length=3,
                        verbose_name="Lian",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data publikasaun")),
                (
                    "file",
                    models.FileField(
                        upload_to=publiku.models.publikasaun_path,
                        verbose_name="File PDF",
                    ),
                ),
                ("tamanu", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("PUBLIKADU", "Publikadu")],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publikasaun",
                "verbose_name_plural": "Publikasaun",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
