# Generated by Django 5.2.17 on 2026-09-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstraguPatrimoniu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Estragu Patrimóniu",
                "verbose_name_plural": "Estragu Patrimóniu",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Munisipiu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Munisípiu",
                "verbose_name_plural": "Munisípiu",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NesesidadeUrjente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Nesesidade Urjente",
                "verbose_name_plural": "Nesesidade Urjente",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pozisaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Pozisaun",
                "verbose_name_plural": "Pozisaun",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipuAtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Tipu Atór",
                "verbose_name_plural": "Tipu Atór",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipuEviksaun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Tipu Eviksaun",
                "verbose_name_plural": "Tipu Eviksaun",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipuKonflitu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "presiza_esplika",
                    models.BooleanField(
                        default=False, verbose_name="Presiza esplikasaun (Seluk)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipu Konflitu Rai",
                "verbose_name_plural": "Tipu Konflitu Rai",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipuRai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Tipu Rai",
                "verbose_name_plural": "Tipu Rai",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostuAdministrativu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "munisipiu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postu_set",
                        to="custom.munisipiu",
                        verbose_name="Munisípiu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postu Administrativu",
                "verbose_name_plural": "Postu Administrativu",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Suku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "postu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suku_set",
                        to="custom.postuadministrativu",
                        verbose_name="Postu Administrativu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suku",
                "verbose_name_plural": "Suku",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aldeia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Kódigu"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "suku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aldeia_set",
                        to="custom.suku",
                        verbose_name="Suku",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aldeia",
                "verbose_name_plural": "Aldeia",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
    ]
